batch_size: 1024
embed_size: 64
layer_size: '[64,64]'
max_lr: 0.0001
step_step_size: 200
reduce_rate: 0.1
mess_dropout: '[0.1,0.1,0.1]'
node_dropout: '[0.1]'
node_dropout_flag: 1
regs: 0.001
max_epoch: 5000
valid_flag: 10